name: Deployment

concurrency: production

on:
  push:
    branches: [main]

jobs:
  deployment:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Display .env content
        run: cat .env

      - name: Export environment variables
        run: |
          export $(grep -v '^#' .env | xargs)

      - name: Build app
        run: scripts/buildprod.sh

      - name: Start app
        run: ./notely
