name: Deploy

concurrency: production

on:
  push:
    branches: [main]

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '>=1.22.5'
      # Build app
      - run: scripts/buildsprod.sh



